name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
      - ci

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - run: mkdir public

      - name: Build Index
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: public/index.html
          github-corners: https://github.com/dvojak-cz/edge-operator

      - uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - uses: actions/deploy-pages@v1
